### ISSUE TITLE
[Getting Started] Error saat migrate database

### ISSUE THREAD

**Issue by leo-tiofan** [coronatorid/altair#2]
Saya mendapatkan log error berikut setelah menjalankan command `docker run --volume $(pwd):/opt/altair --entrypoint altair codefluence/altair migrate main_database`

`{"level":"info","message":"Complete fabricating mysql writer connection: dev_coronatorid:***********@tcp(DB_HOST.2:3306)/altair_coronator_development?","tags":["altair","main"],"timestamp":"2021-01-30T13:29:42.624135495Z","track_id":"20ab5734-3ccc-4e3b-8ca7-18853a80543d"}
{"caller":"/home/muhammad/project/codefluence/altair/altair.go:166","error":"Error 1045: Access denied for user 'DB_USER'@'_gateway' (using password: YES)","level":"error","message":"Error providing migrator","tags":["altair","main"],"timestamp":"2021-01-30T13:29:50.041830625Z","track_id":"5616d48b-062e-46da-a948-6edce25298b8"}
{"level":"info","message":"Success closing mysql writer and reader connection.","tags":["altair","main","main_database"],"timestamp":"2021-01-30T13:29:50.042184816Z","track_id":"a9c3de82-cf60-44e5-8762-9239d12be18a"}`

**Comment by insomnius** [comment]
Halo @leotj , boleh sertakan isi .env file mu?

**Comment by leo-tiofan** [comment]
# App config
APP_ENV=local
ACCESS_TOKEN_TIMEOUT=24h
ACCESS_GRANT_TIMEOUT=2h

# Database configuration
DATABASE_HOST=192.x.y.z
DATABASE_PORT=3306
DATABASE_NAME=altair_coronator_development
DATABASE_USERNAME=[removed]
DATABASE_PASSWORD=[removed]

# Basic auth configuration
BASIC_AUTH_USERNAME=altair
BASIC_AUTH_PASSWORD=eaglethatflyinthebluesky

PROXY_HOST=www.local.host

CORONATOR_HOST=www.local.host:2019

**Comment by insomnius** [comment]
OS yang dipakai apa ya @leotj ? Kalau dari error-nya itu karena tidak bisa terkoneksi dengan database.

**Comment by leo-tiofan** [comment]
OS: MacOS
Database: Percona MySQL 8.x (multipass: ubuntu virtual)
Biasanya untuk database install-nya seperti apa? @insomnius

**Comment by insomnius** [comment]
I see, databasenya di virtual machine.


Untuk troubleshooting mungkin bisa coba disini mas: https://www.percona.com/blog/2019/07/05/fixing-a-mysql-1045-error/

Jadi masuk ke dockernya altair lalu lakukan integration test disana.


Cara lain:

1. Clone http://github.com/codefluence-x/altair
2. Build binary-nya menggunakan `make build`
3. Copy binary ke folder coronatorid/altair
4. Lalu jalankan dg `./altair migrate main_database`
5. `./altair run`

**Comment by leo-tiofan** [comment]
Hi mas @insomnius 

Issue-nya solved ya mas, penyebabnya karena saya menggunakan special character di env untuk password database.
Solusinya, saya perlu menggunakan "" untuk passwordnya.

**Comment by insomnius** [comment]
Ah i see, siap sama2 mas @leotj .
